### ISSUE TITLE
Crimean hakaton - february\2018 - prize fund

### ISSUE THREAD

**Issue by serejandmyself** [cyberFund/golosfund#38]

**Comment by serejandmyself** [comment]
Has been diceded on

**Comment by Kwaskoff** [comment]
8500 GOLOS @vittigo
8500 GOLOS @devman10
5000 GOLOS @votehunter
3000 GOLOS @pahatrop
1000 GOLOS @deeebug
1000 GOLOS @souls
1000 GOLOS @itsphere
1000 GOLOS @drinkchain
1000 GOLOS @tkashkin

**Comment by serejandmyself** [comment]
To pay out

**Comment by serejandmyself** [comment]
https://golos.io/@golos/transfers
