### ISSUE TITLE
Make a content plan for each of the SM channels

### ISSUE THREAD

**Issue by marchmallow8** [cyberFund/golosfund#61]

**Comment by marchmallow8** [comment]
It's done..Waiting for comments 
[Content_Plan .xlsx](https://github.com/cyberFund/golosfund/files/1729268/Content_Plan.xlsx)
will upload information according to the  plan, tomorrow. Hope for some help and information in regards to the history of fund formation ( text for Monday ) . Also need some help for writing an article for Medium ( need 2 articles  a week in english ) any ideas?

**Comment by serejandmyself** [comment]
Missing twitter + telegram + golos + steem. 
steem + medium - once a week is more than enough

**Comment by marchmallow8** [comment]
https://twitter.com/goloschain  twitter  есть   telegram  -тот что Олеся открыла? Golos и steem тоже есть

**Comment by marchmallow8** [comment]
Content plan done. And filled with initial content for a week.

**Comment by marchmallow8** [comment]
Done!
